# Generated by Django 4.1 on 2023-12-15 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 15, 12, 29, 32, 200558, tzinfo=datetime.timezone.utc)),
        ),
    ]
