# Generated by Django 4.1 on 2023-12-22 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 22, 17, 52, 7, 117105, tzinfo=datetime.timezone.utc)),
        ),
    ]
