# Generated by Django 4.1 on 2023-12-22 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_image_alter_product_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 22, 21, 3, 40, 39071, tzinfo=datetime.timezone.utc)),
        ),
    ]
